server:
  port: 8080
spring:
  application:
    name: address
  datasource:
    url: jdbc:postgresql://159.31.70.104:5432/mines
    password: mines
    username: mines

logging:
  level:
    org:
     springframework:
       web: DEBUG